Repository BuildForSDG/Mental-Remedy, pull requests merged in 2020-06, with the labels that each got.

#57 List Filter
  .eslintrc.js
  package.json
  src/App.css
  src/app.js
  src/context/Context.js
  src/context/data.js
  src/filter/Filter.js
  src/filter/Filter.test.js
  src/filter/FilterByCity.js
  src/filter/FilterByName.js
  src/filter/FilterByTitle.js
  src/index.js
  src/intro/IntroHeader.js
  src/mental-disorders/Md.js
  src/mental-disorders/Md.test.js
  src/mental-disorders/MdList.js
  src/mental-disorders/MdMain.js
  src/navbar/DropDown.js
  src/navbar/DropDownLink.js
  src/navbar/NavItem.js
  src/navbar/NavList.js
  src/navbar/navbar.test.js
  src/pages/MentalDisorders.js
  src/pages/SpecialistsPage.js
  src/sp-Page/Specialist.js
  src/sp-Page/Specialists.js
  src/sp-Page/Specialists.test.js
  src/sp-Page/SpecialistsList.js
  yarn.lock
Labels: user

#61 About
  src/App.css
  src/app.js
  src/pages/AboutPage.js
  yarn.lock
Labels: user

#64 Mental Disorder details page
  .DS_Store
  package.json
  src/App.css
  src/app.js
  src/context/data.js
  src/mdList-preview/MdPreview.js
  src/mdList-preview/MdPreview.test.js
  src/mental-disorders/Md.js
  src/mental-disorders/Md.test.js
  src/pages/AboutPage.js
  src/pages/LandingPage.js
  src/pages/MentalDisorders.js
  src/pages/SingleMdPage.js
  src/pages/SpecialistsPage.js
  src/single-md/SingleMd.js
  src/single-md/SingleMd.test.js
  src/sp-Page/Specialists.test.js
  src/specialists/SpecialistsPrev.js
  src/specialists/SpecialistsPrev.test.js
  src/swiper.js
  yarn.lock
Labels: enhancement

#69 Ft appointment
  .eslintrc.js
  .gitignore
  src/App.css
  src/app.js
  src/context/data.js
  src/pages/AppointmentsPage.js
  src/pages/SingleSpPage.js
  src/single-sp/Form.js
  src/single-sp/SingleSp.js
  src/sp-Page/Specialist.js
Labels: user

#68 App properties
  README.md
  app.properties
  readme.png
Labels: documentation

#66 Read me
  README.md
  src/mental-disorders/AddSymptomForm.js
Labels: user
