Repository BuildForSDG/Mental-Remedy, pull requests merged in 2020-05, with the labels that each got.

#2 linting config
  .github/workflows/lint.yml
  jest.config.js
  src/index.js
Labels: good first issue

#6 React installation
  .babelrc
  .github/workflows/lint.yml
  package.json
  yarn.lock
Labels: enhancement

#8 first react component
  .eslintrc.js
  .github/workflows/lint.yml
  __tests__/app.test.js
  package.json
  src/app.js
  src/index.html
  src/index.js
  yarn.lock
Labels: enhancement

#12 css variables for the theme
  .babelrc
  .eslintrc.js
  README.md
  __tests__/app.test.js
  jest.config.js
  package.json
  src/App.css
  src/app.js
  src/fonts.css
  src/index.css
  src/index.js
Labels: enhancement

#15 landing-page-setup
  src/App.css
  src/app.js
  src/pages/LandingPage.js
Labels: enhancement

#17 intro header
  src/App.css
  src/pages/LandingPage.js
Labels: enhancement

#18 Navbar component
  .eslintrc.js
  package.json
  src/App.css
  src/app.js
  src/index.css
  src/navbar/NavBar.js
  src/navbar/NavItem.js
  src/navbar/NavList.js
  src/pages/LandingPage.js
  yarn.lock
Labels: enhancement

#20 Tests for each component
  __tests__/app.test.js
  jest.config.js
  package.json
  src/app.test.js
  src/navbar/NavBar.js
  src/navbar/navbar.test.js
  yarn.lock
Labels: enhancement

#21 IntroHeader Testing
  src/app.test.js
  src/intro/IntroHeader.js
  src/intro/IntroHeader.test.js
  src/navbar/navbar.test.js
  src/pages/LandingPage.js
Labels: enhancement

#25 Context API
  .eslintrc.js
  src/App.css
  src/context/Context.js
  src/context/Context.test.js
Labels: enhancement

#23 About Component setup
  .eslintrc.js
  src/About/About.Test.js
  src/About/About.js
  src/About/Bio.js
  src/About/Service.js
  src/About/ServiceList.js
  src/About/Services.js
  src/App.css
  src/app.js
  src/context/Context.js
  src/context/data.js
  src/context/images/appointment.svg
  src/context/images/awareness.svg
  src/context/images/forum.svg
  src/context/images/specialist.svg
  src/index.html
  src/pages/LandingPage.js
Labels: enhancement

#29 fixed failed tests
  jest.config.js
  mockSVG.js
  src/context/Context.js
Labels: bug

#30 About
  package.json
  src/About/Service.js
  src/About/ServiceList.js
  src/About/Services.js
  src/App.css
  src/context/Context.js
  src/context/Context.test.js
  src/context/data.js
  src/navbar/NavBar.js
  src/navbar/NavItem.js
  src/navbar/NavList.js
  src/navbar/navbar.test.js
Labels: enhancement

#32 Sample list of mental disorders
  src/context/data.js
Labels: enhancement

#33 specialists-data
  .eslintrc.js
  src/context/data.js
  src/context/images/female.svg
  src/context/images/male.svg
Labels: enhancement

#34 Dropdown menu
  .eslintrc.js
  src/App.css
  src/context/Context.js
  src/navbar/DropDown.js
  src/navbar/DropDownLink.js
  src/navbar/NavBar.js
  src/navbar/NavItem.js
  src/navbar/NavList.js
Labels: enhancement

#36 Specialist preview
  .eslintrc.js
  src/App.css
  src/context/Context.js
  src/context/data.js
  src/pages/LandingPage.js
  src/specialists/Specialist.js
  src/specialists/SpecialistsLists.js
  src/specialists/SpecialistsPrev.js
  src/specialists/SpecialistsPrev.test.js
Labels: enhancement

#38 Mental Disorders preview
  .eslintrc.js
  package.json
  src/About/About.Test.js
  src/About/About.test.js
  src/About/Bio.js
  src/About/ServiceList.js
  src/App.css
  src/context/Context.js
  src/context/data.js
  src/index.css
  src/mdList-preview/MdItemPreview.js
  src/mdList-preview/MdListPreview.js
  src/mdList-preview/MdPreview.js
  src/mdList-preview/MdPreview.test.js
  src/navbar/DropDown.js
  src/navbar/DropDownLink.js
  src/navbar/NavBar.js
  src/navbar/NavItem.js
  src/navbar/NavList.js
  src/navbar/navbar.test.js
  src/pages/LandingPage.js
  yarn.lock
Labels: enhancement

#52 Specialist preview slider
  package.json
  src/App.css
  src/context/Context.js
  src/context/data.js
  src/index.css
  src/index.js
  src/mdList-preview/MdItemPreview.js
  src/specialists/Specialist.js
  src/specialists/SpecialistsLists.js
  src/specialists/SpecialistsPrev.js
  src/specialists/SpecialistsPrev.test.js
  src/swiper.js
  yarn.lock
Labels: enhancement

#53 Footer
  .eslintrc.js
  package.json
  src/App.css
  src/app.js
  src/footer/Footer.js
  src/index.css
  yarn.lock
Labels: good first issue
